PackageIdentifier: TuringLambda.MoveBit
PackageVersion: 1.4.0
MinimumOSVersion: 10.0.17763.0
InstallerLocale: en-US
InstallerType: inno
Scope: user
UpgradeBehavior: install
InstallerUrl: https://github.com/turinglambdaai/movebit/releases/download/v1.4.0/MoveBit-Setup-windows-x64.exe
InstallerSha256: A13590355D5034D20524D4E80B560B7C32D1374504EDDA73EA9A67D709ED1639
ProductCode: '{E4B9E01D-65D0-4C25-BCF1-3CC22B8C9E02}_is1'
AppsAndFeaturesEntries:
- DisplayName: MoveBit
  Publisher: turinglambdaai
  DisplayVersion: 1.4.0
  ProductCode: '{E4B9E01D-65D0-4C25-BCF1-3CC22B8C9E02}_is1'
ManifestType: installer
ManifestVersion: 1.6.0
