PackageIdentifier: TuringLambda.HackDigest
PackageVersion: 0.5.1
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
InstallerUrl: https://github.com/turinglambdaai/hackdigest/releases/download/v0.5.1/HackDigest_0.5.1_x64-setup.exe
InstallerSha256: A914D1AA5234A3258C188E1CD421D85FE584BC759A38BB173EF8640AA3BE4D42
ProductCode: HackDigest
AppsAndFeaturesEntries:
- DisplayName: HackDigest
  Publisher: jrtx
  DisplayVersion: 0.5.1
  ProductCode: HackDigest
ManifestType: installer
ManifestVersion: 1.6.0
