# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: TuringLambdaAI.RegexMate
PackageVersion: 0.2.1
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/turinglambdaai/regexmate/releases/download/v0.2.1/regexmate-standalone-windows-x86_64-v0.2.1.exe
    InstallerSha256: BE5ABA553AF70B8785C6E0C250D62EB74E0654D1E832A41671053783E45707AD
    Commands:
      - regexmate
ManifestType: installer
ManifestVersion: 1.6.0
