PackageIdentifier: TuringLambda.PodLens
PackageVersion: 1.2.0
MinimumOSVersion: 10.0.19041.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
InstallerUrl: https://github.com/turinglambdaai/podlens/releases/download/v1.2.0/podlens-1.2.0-windows-x64.msi
InstallerSha256: 073D458CFFA602AE1A0DE2E19A809D20D3B05FC63FDEC1A9AC10CAA665ED3B97
ProductCode: '{4514663E-753D-4960-B7CF-BD103A9A7F39}'
AppsAndFeaturesEntries:
- DisplayName: PodLens
  Publisher: site.jrtx.podlens
  DisplayVersion: 1.2.0
  ProductCode: '{4514663E-753D-4960-B7CF-BD103A9A7F39}'
  UpgradeCode: '{CB5A967A-57C6-5416-BCAF-0369D6F47923}'
ManifestType: installer
ManifestVersion: 1.6.0
